{
 "title": "Go Runtime",
 "description": "Go runtime metrics from OpenTelemetry provider.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(go_goroutines,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mode",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "demo_mode", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Goroutine Count",
   "type": "timeseries",
   "description": "Count of live goroutines.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max by(instance) (go_goroutines{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "description": "Count of live threads.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "max by(instance) (go_threads{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "description": "Memory used by the Go runtime.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(instance) (go_memstats_heap_alloc_bytes{job=~\"$job\"})",
     "legendFormat": "heap {{instance}}"
    },
    {
     "expr": "max by(instance) (go_memstats_sys_bytes{job=~\"$job\"})",
     "legendFormat": "sys {{instance}}"
    }
   ]
  },
  {
   "title": "Memory allocations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\"}[$__rate_interval])\n",
     "legendFormat": "heap {{instance}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  rate(go_gc_duration_seconds_sum{job=~\"$job\"}[$__rate_interval]) / \n  rate(go_gc_duration_seconds_count{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}